services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    env_file:
      - .env
    volumes:
      - ollama-vol:/root/.ollama
    networks:
      - ollama-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['0']
  
  ollama-pull:
    container_name: ollama-pull
    image: docker/genai:ollama-pull
    depends_on:
      - ollama
    env_file:
      - .env

  ollama-fastapi:
    container_name: ollama-fastapi
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 1010 --log-level debug --forwarded-allow-ips --reload
    depends_on:
      - ollama
      - ollama-pull
    ports:
      - "1010:1010"
    env_file:
      - .env
    volumes:
      - .:/workdir
    networks:
      - ollama-net
    restart: on-failure
    healthcheck:
      test: curl --fail http://localhost:1010/ || exit 1
      interval: 60s 
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  ollama-vol:

networks:
  ollama-net:
    name: ollama-net
    driver: bridge